export type mathFontface =
  | 'serif-bold'
  | 'serif-italic'
  | 'serif-bolditalic'
  | 'sans-bold'
  | 'sans-italic'
  | 'sans-normal'
  | 'sans-bolditalic'
  | 'script-normal'
  | 'script-bold'
  | 'fraktur-normal'
  | 'fraktur-bold'
  | 'monospace-normal'
  | 'doublestruck-normal';

export const mathFonts: {
  [letter: string]: Partial<Record<mathFontface, string>>;
} = {
  // courtesy of
  // https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols
  // and sublime text's multiple cursors
  A: {
    'serif-bold': '𝐀',
    'serif-italic': '𝐴',
    'serif-bolditalic': '𝑨',
    'sans-normal': '𝖠',
    'sans-bold': '𝗔',
    'sans-italic': '𝘈',
    'sans-bolditalic': '𝘼',
    'script-normal': '𝒜',
    'script-bold': '𝓐',
    'fraktur-normal': '𝔄',
    'fraktur-bold': '𝕬',
    'monospace-normal': '𝙰',
    'doublestruck-normal': '𝔸',
  },
  B: {
    'serif-bold': '𝐁',
    'serif-italic': '𝐵',
    'serif-bolditalic': '𝑩',
    'sans-normal': '𝖡',
    'sans-bold': '𝗕',
    'sans-italic': '𝘉',
    'sans-bolditalic': '𝘽',
    'script-normal': 'ℬ',
    'script-bold': '𝓑',
    'fraktur-normal': '𝔅',
    'fraktur-bold': '𝕭',
    'monospace-normal': '𝙱',
    'doublestruck-normal': '𝔹',
  },
  C: {
    'serif-bold': '𝐂',
    'serif-italic': '𝐶',
    'serif-bolditalic': '𝑪',
    'sans-normal': '𝖢',
    'sans-bold': '𝗖',
    'sans-italic': '𝘊',
    'sans-bolditalic': '𝘾',
    'script-normal': '𝒞',
    'script-bold': '𝓒',
    'fraktur-normal': 'ℭ',
    'fraktur-bold': '𝕮',
    'monospace-normal': '𝙲',
    'doublestruck-normal': 'ℂ',
  },
  D: {
    'serif-bold': '𝐃',
    'serif-italic': '𝐷',
    'serif-bolditalic': '𝑫',
    'sans-normal': '𝖣',
    'sans-bold': '𝗗',
    'sans-italic': '𝘋',
    'sans-bolditalic': '𝘿',
    'script-normal': '𝒟',
    'script-bold': '𝓓',
    'fraktur-normal': '𝔇',
    'fraktur-bold': '𝕯',
    'monospace-normal': '𝙳',
    'doublestruck-normal': '𝔻',
  },
  E: {
    'serif-bold': '𝐄',
    'serif-italic': '𝐸',
    'serif-bolditalic': '𝑬',
    'sans-normal': '𝖤',
    'sans-bold': '𝗘',
    'sans-italic': '𝘌',
    'sans-bolditalic': '𝙀',
    'script-normal': 'ℰ',
    'script-bold': '𝓔',
    'fraktur-normal': '𝔈',
    'fraktur-bold': '𝕰',
    'monospace-normal': '𝙴',
    'doublestruck-normal': '𝔼',
  },
  F: {
    'serif-bold': '𝐅',
    'serif-italic': '𝐹',
    'serif-bolditalic': '𝑭',
    'sans-normal': '𝖥',
    'sans-bold': '𝗙',
    'sans-italic': '𝘍',
    'sans-bolditalic': '𝙁',
    'script-normal': 'ℱ',
    'script-bold': '𝓕',
    'fraktur-normal': '𝔉',
    'fraktur-bold': '𝕱',
    'monospace-normal': '𝙵',
    'doublestruck-normal': '𝔽',
  },
  G: {
    'serif-bold': '𝐆',
    'serif-italic': '𝐺',
    'serif-bolditalic': '𝑮',
    'sans-normal': '𝖦',
    'sans-bold': '𝗚',
    'sans-italic': '𝘎',
    'sans-bolditalic': '𝙂',
    'script-normal': '𝒢',
    'script-bold': '𝓖',
    'fraktur-normal': '𝔊',
    'fraktur-bold': '𝕲',
    'monospace-normal': '𝙶',
    'doublestruck-normal': '𝔾',
  },
  H: {
    'serif-bold': '𝐇',
    'serif-italic': '𝐻',
    'serif-bolditalic': '𝑯',
    'sans-normal': '𝖧',
    'sans-bold': '𝗛',
    'sans-italic': '𝘏',
    'sans-bolditalic': '𝙃',
    'script-normal': 'ℋ',
    'script-bold': '𝓗',
    'fraktur-normal': 'ℌ',
    'fraktur-bold': '𝕳',
    'monospace-normal': '𝙷',
    'doublestruck-normal': 'ℍ',
  },
  I: {
    'serif-bold': '𝐈',
    'serif-italic': '𝐼',
    'serif-bolditalic': '𝑰',
    'sans-normal': '𝖨',
    'sans-bold': '𝗜',
    'sans-italic': '𝘐',
    'sans-bolditalic': '𝙄',
    'script-normal': 'ℐ',
    'script-bold': '𝓘',
    'fraktur-normal': 'ℑ',
    'fraktur-bold': '𝕴',
    'monospace-normal': '𝙸',
    'doublestruck-normal': '𝕀',
  },
  J: {
    'serif-bold': '𝐉',
    'serif-italic': '𝐽',
    'serif-bolditalic': '𝑱',
    'sans-normal': '𝖩',
    'sans-bold': '𝗝',
    'sans-italic': '𝘑',
    'sans-bolditalic': '𝙅',
    'script-normal': '𝒥',
    'script-bold': '𝓙',
    'fraktur-normal': '𝔍',
    'fraktur-bold': '𝕵',
    'monospace-normal': '𝙹',
    'doublestruck-normal': '𝕁',
  },
  K: {
    'serif-bold': '𝐊',
    'serif-italic': '𝐾',
    'serif-bolditalic': '𝑲',
    'sans-normal': '𝖪',
    'sans-bold': '𝗞',
    'sans-italic': '𝘒',
    'sans-bolditalic': '𝙆',
    'script-normal': '𝒦',
    'script-bold': '𝓚',
    'fraktur-normal': '𝔎',
    'fraktur-bold': '𝕶',
    'monospace-normal': '𝙺',
    'doublestruck-normal': '𝕂',
  },
  L: {
    'serif-bold': '𝐋',
    'serif-italic': '𝐿',
    'serif-bolditalic': '𝑳',
    'sans-normal': '𝖫',
    'sans-bold': '𝗟',
    'sans-italic': '𝘓',
    'sans-bolditalic': '𝙇',
    'script-normal': 'ℒ',
    'script-bold': '𝓛',
    'fraktur-normal': '𝔏',
    'fraktur-bold': '𝕷',
    'monospace-normal': '𝙻',
    'doublestruck-normal': '𝕃',
  },
  M: {
    'serif-bold': '𝐌',
    'serif-italic': '𝑀',
    'serif-bolditalic': '𝑴',
    'sans-normal': '𝖬',
    'sans-bold': '𝗠',
    'sans-italic': '𝘔',
    'sans-bolditalic': '𝙈',
    'script-normal': 'ℳ',
    'script-bold': '𝓜',
    'fraktur-normal': '𝔐',
    'fraktur-bold': '𝕸',
    'monospace-normal': '𝙼',
    'doublestruck-normal': '𝕄',
  },
  N: {
    'serif-bold': '𝐍',
    'serif-italic': '𝑁',
    'serif-bolditalic': '𝑵',
    'sans-normal': '𝖭',
    'sans-bold': '𝗡',
    'sans-italic': '𝘕',
    'sans-bolditalic': '𝙉',
    'script-normal': '𝒩',
    'script-bold': '𝓝',
    'fraktur-normal': '𝔑',
    'fraktur-bold': '𝕹',
    'monospace-normal': '𝙽',
    'doublestruck-normal': 'ℕ',
  },
  O: {
    'serif-bold': '𝐎',
    'serif-italic': '𝑂',
    'serif-bolditalic': '𝑶',
    'sans-normal': '𝖮',
    'sans-bold': '𝗢',
    'sans-italic': '𝘖',
    'sans-bolditalic': '𝙊',
    'script-normal': '𝒪',
    'script-bold': '𝓞',
    'fraktur-normal': '𝔒',
    'fraktur-bold': '𝕺',
    'monospace-normal': '𝙾',
    'doublestruck-normal': '𝕆',
  },
  P: {
    'serif-bold': '𝐏',
    'serif-italic': '𝑃',
    'serif-bolditalic': '𝑷',
    'sans-normal': '𝖯',
    'sans-bold': '𝗣',
    'sans-italic': '𝘗',
    'sans-bolditalic': '𝙋',
    'script-normal': '𝒫',
    'script-bold': '𝓟',
    'fraktur-normal': '𝔓',
    'fraktur-bold': '𝕻',
    'monospace-normal': '𝙿',
    'doublestruck-normal': 'ℙ',
  },
  Q: {
    'serif-bold': '𝐐',
    'serif-italic': '𝑄',
    'serif-bolditalic': '𝑸',
    'sans-normal': '𝖰',
    'sans-bold': '𝗤',
    'sans-italic': '𝘘',
    'sans-bolditalic': '𝙌',
    'script-normal': '𝒬',
    'script-bold': '𝓠',
    'fraktur-normal': '𝔔',
    'fraktur-bold': '𝕼',
    'monospace-normal': '𝚀',
    'doublestruck-normal': 'ℚ',
  },
  R: {
    'serif-bold': '𝐑',
    'serif-italic': '𝑅',
    'serif-bolditalic': '𝑹',
    'sans-normal': '𝖱',
    'sans-bold': '𝗥',
    'sans-italic': '𝘙',
    'sans-bolditalic': '𝙍',
    'script-normal': 'ℛ',
    'script-bold': '𝓡',
    'fraktur-normal': 'ℜ',
    'fraktur-bold': '𝕽',
    'monospace-normal': '𝚁',
    'doublestruck-normal': 'ℝ',
  },
  S: {
    'serif-bold': '𝐒',
    'serif-italic': '𝑆',
    'serif-bolditalic': '𝑺',
    'sans-normal': '𝖲',
    'sans-bold': '𝗦',
    'sans-italic': '𝘚',
    'sans-bolditalic': '𝙎',
    'script-normal': '𝒮',
    'script-bold': '𝓢',
    'fraktur-normal': '𝔖',
    'fraktur-bold': '𝕾',
    'monospace-normal': '𝚂',
    'doublestruck-normal': '𝕊',
  },
  T: {
    'serif-bold': '𝐓',
    'serif-italic': '𝑇',
    'serif-bolditalic': '𝑻',
    'sans-normal': '𝖳',
    'sans-bold': '𝗧',
    'sans-italic': '𝘛',
    'sans-bolditalic': '𝙏',
    'script-normal': '𝒯',
    'script-bold': '𝓣',
    'fraktur-normal': '𝔗',
    'fraktur-bold': '𝕿',
    'monospace-normal': '𝚃',
    'doublestruck-normal': '𝕋',
  },
  U: {
    'serif-bold': '𝐔',
    'serif-italic': '𝑈',
    'serif-bolditalic': '𝑼',
    'sans-normal': '𝖴',
    'sans-bold': '𝗨',
    'sans-italic': '𝘜',
    'sans-bolditalic': '𝙐',
    'script-normal': '𝒰',
    'script-bold': '𝓤',
    'fraktur-normal': '𝔘',
    'fraktur-bold': '𝖀',
    'monospace-normal': '𝚄',
    'doublestruck-normal': '𝕌',
  },
  V: {
    'serif-bold': '𝐕',
    'serif-italic': '𝑉',
    'serif-bolditalic': '𝑽',
    'sans-normal': '𝖵',
    'sans-bold': '𝗩',
    'sans-italic': '𝘝',
    'sans-bolditalic': '𝙑',
    'script-normal': '𝒱',
    'script-bold': '𝓥',
    'fraktur-normal': '𝔙',
    'fraktur-bold': '𝖁',
    'monospace-normal': '𝚅',
    'doublestruck-normal': '𝕍',
  },
  W: {
    'serif-bold': '𝐖',
    'serif-italic': '𝑊',
    'serif-bolditalic': '𝑾',
    'sans-normal': '𝖶',
    'sans-bold': '𝗪',
    'sans-italic': '𝘞',
    'sans-bolditalic': '𝙒',
    'script-normal': '𝒲',
    'script-bold': '𝓦',
    'fraktur-normal': '𝔚',
    'fraktur-bold': '𝖂',
    'monospace-normal': '𝚆',
    'doublestruck-normal': '𝕎',
  },
  X: {
    'serif-bold': '𝐗',
    'serif-italic': '𝑋',
    'serif-bolditalic': '𝑿',
    'sans-normal': '𝖷',
    'sans-bold': '𝗫',
    'sans-italic': '𝘟',
    'sans-bolditalic': '𝙓',
    'script-normal': '𝒳',
    'script-bold': '𝓧',
    'fraktur-normal': '𝔛',
    'fraktur-bold': '𝖃',
    'monospace-normal': '𝚇',
    'doublestruck-normal': '𝕏',
  },
  Y: {
    'serif-bold': '𝐘',
    'serif-italic': '𝑌',
    'serif-bolditalic': '𝒀',
    'sans-normal': '𝖸',
    'sans-bold': '𝗬',
    'sans-italic': '𝘠',
    'sans-bolditalic': '𝙔',
    'script-normal': '𝒴',
    'script-bold': '𝓨',
    'fraktur-normal': '𝔜',
    'fraktur-bold': '𝖄',
    'monospace-normal': '𝚈',
    'doublestruck-normal': '𝕐',
  },
  Z: {
    'serif-bold': '𝐙',
    'serif-italic': '𝑍',
    'serif-bolditalic': '𝒁',
    'sans-normal': '𝖹',
    'sans-bold': '𝗭',
    'sans-italic': '𝘡',
    'sans-bolditalic': '𝙕',
    'script-normal': '𝒵',
    'script-bold': '𝓩',
    'fraktur-normal': 'ℨ',
    'fraktur-bold': '𝖅',
    'monospace-normal': '𝚉',
    'doublestruck-normal': 'ℤ',
  },
  a: {
    'serif-bold': '𝐚',
    'serif-italic': '𝑎',
    'serif-bolditalic': '𝒂',
    'sans-normal': '𝖺',
    'sans-bold': '𝗮',
    'sans-italic': '𝘢',
    'sans-bolditalic': '𝙖',
    'script-normal': '𝒶',
    'script-bold': '𝓪',
    'fraktur-normal': '𝔞',
    'fraktur-bold': '𝖆',
    'monospace-normal': '𝚊',
    'doublestruck-normal': '𝕒',
  },
  b: {
    'serif-bold': '𝐛',
    'serif-italic': '𝑏',
    'serif-bolditalic': '𝒃',
    'sans-normal': '𝖻',
    'sans-bold': '𝗯',
    'sans-italic': '𝘣',
    'sans-bolditalic': '𝙗',
    'script-normal': '𝒷',
    'script-bold': '𝓫',
    'fraktur-normal': '𝔟',
    'fraktur-bold': '𝖇',
    'monospace-normal': '𝚋',
    'doublestruck-normal': '𝕓',
  },
  c: {
    'serif-bold': '𝐜',
    'serif-italic': '𝑐',
    'serif-bolditalic': '𝒄',
    'sans-normal': '𝖼',
    'sans-bold': '𝗰',
    'sans-italic': '𝘤',
    'sans-bolditalic': '𝙘',
    'script-normal': '𝒸',
    'script-bold': '𝓬',
    'fraktur-normal': '𝔠',
    'fraktur-bold': '𝖈',
    'monospace-normal': '𝚌',
    'doublestruck-normal': '𝕔',
  },
  d: {
    'serif-bold': '𝐝',
    'serif-italic': '𝑑',
    'serif-bolditalic': '𝒅',
    'sans-normal': '𝖽',
    'sans-bold': '𝗱',
    'sans-italic': '𝘥',
    'sans-bolditalic': '𝙙',
    'script-normal': '𝒹',
    'script-bold': '𝓭',
    'fraktur-normal': '𝔡',
    'fraktur-bold': '𝖉',
    'monospace-normal': '𝚍',
    'doublestruck-normal': '𝕕',
  },
  e: {
    'serif-bold': '𝐞',
    'serif-italic': '𝑒',
    'serif-bolditalic': '𝒆',
    'sans-normal': '𝖾',
    'sans-bold': '𝗲',
    'sans-italic': '𝘦',
    'sans-bolditalic': '𝙚',
    'script-normal': 'ℯ',
    'script-bold': '𝓮',
    'fraktur-normal': '𝔢',
    'fraktur-bold': '𝖊',
    'monospace-normal': '𝚎',
    'doublestruck-normal': '𝕖',
  },
  f: {
    'serif-bold': '𝐟',
    'serif-italic': '𝑓',
    'serif-bolditalic': '𝒇',
    'sans-normal': '𝖿',
    'sans-bold': '𝗳',
    'sans-italic': '𝘧',
    'sans-bolditalic': '𝙛',
    'script-normal': '𝒻',
    'script-bold': '𝓯',
    'fraktur-normal': '𝔣',
    'fraktur-bold': '𝖋',
    'monospace-normal': '𝚏',
    'doublestruck-normal': '𝕗',
  },
  g: {
    'serif-bold': '𝐠',
    'serif-italic': '𝑔',
    'serif-bolditalic': '𝒈',
    'sans-normal': '𝗀',
    'sans-bold': '𝗴',
    'sans-italic': '𝘨',
    'sans-bolditalic': '𝙜',
    'script-normal': 'ℊ',
    'script-bold': '𝓰',
    'fraktur-normal': '𝔤',
    'fraktur-bold': '𝖌',
    'monospace-normal': '𝚐',
    'doublestruck-normal': '𝕘',
  },
  h: {
    'serif-bold': '𝐡',
    'serif-italic': 'ℎ',
    'serif-bolditalic': '𝒉',
    'sans-normal': '𝗁',
    'sans-bold': '𝗵',
    'sans-italic': '𝘩',
    'sans-bolditalic': '𝙝',
    'script-normal': '𝒽',
    'script-bold': '𝓱',
    'fraktur-normal': '𝔥',
    'fraktur-bold': '𝖍',
    'monospace-normal': '𝚑',
    'doublestruck-normal': '𝕙',
  },
  i: {
    'serif-bold': '𝐢',
    'serif-italic': '𝑖',
    'serif-bolditalic': '𝒊',
    'sans-normal': '𝗂',
    'sans-bold': '𝗶',
    'sans-italic': '𝘪',
    'sans-bolditalic': '𝙞',
    'script-normal': '𝒾',
    'script-bold': '𝓲',
    'fraktur-normal': '𝔦',
    'fraktur-bold': '𝖎',
    'monospace-normal': '𝚒',
    'doublestruck-normal': '𝕚',
  },
  j: {
    'serif-bold': '𝐣',
    'serif-italic': '𝑗',
    'serif-bolditalic': '𝒋',
    'sans-normal': '𝗃',
    'sans-bold': '𝗷',
    'sans-italic': '𝘫',
    'sans-bolditalic': '𝙟',
    'script-normal': '𝒿',
    'script-bold': '𝓳',
    'fraktur-normal': '𝔧',
    'fraktur-bold': '𝖏',
    'monospace-normal': '𝚓',
    'doublestruck-normal': '𝕛',
  },
  k: {
    'serif-bold': '𝐤',
    'serif-italic': '𝑘',
    'serif-bolditalic': '𝒌',
    'sans-normal': '𝗄',
    'sans-bold': '𝗸',
    'sans-italic': '𝘬',
    'sans-bolditalic': '𝙠',
    'script-normal': '𝓀',
    'script-bold': '𝓴',
    'fraktur-normal': '𝔨',
    'fraktur-bold': '𝖐',
    'monospace-normal': '𝚔',
    'doublestruck-normal': '𝕜',
  },
  l: {
    'serif-bold': '𝐥',
    'serif-italic': '𝑙',
    'serif-bolditalic': '𝒍',
    'sans-normal': '𝗅',
    'sans-bold': '𝗹',
    'sans-italic': '𝘭',
    'sans-bolditalic': '𝙡',
    'script-normal': '𝓁',
    'script-bold': '𝓵',
    'fraktur-normal': '𝔩',
    'fraktur-bold': '𝖑',
    'monospace-normal': '𝚕',
    'doublestruck-normal': '𝕝',
  },
  m: {
    'serif-bold': '𝐦',
    'serif-italic': '𝑚',
    'serif-bolditalic': '𝒎',
    'sans-normal': '𝗆',
    'sans-bold': '𝗺',
    'sans-italic': '𝘮',
    'sans-bolditalic': '𝙢',
    'script-normal': '𝓂',
    'script-bold': '𝓶',
    'fraktur-normal': '𝔪',
    'fraktur-bold': '𝖒',
    'monospace-normal': '𝚖',
    'doublestruck-normal': '𝕞',
  },
  n: {
    'serif-bold': '𝐧',
    'serif-italic': '𝑛',
    'serif-bolditalic': '𝒏',
    'sans-normal': '𝗇',
    'sans-bold': '𝗻',
    'sans-italic': '𝘯',
    'sans-bolditalic': '𝙣',
    'script-normal': '𝓃',
    'script-bold': '𝓷',
    'fraktur-normal': '𝔫',
    'fraktur-bold': '𝖓',
    'monospace-normal': '𝚗',
    'doublestruck-normal': '𝕟',
  },
  o: {
    'serif-bold': '𝐨',
    'serif-italic': '𝑜',
    'serif-bolditalic': '𝒐',
    'sans-normal': '𝗈',
    'sans-bold': '𝗼',
    'sans-italic': '𝘰',
    'sans-bolditalic': '𝙤',
    'script-normal': 'ℴ',
    'script-bold': '𝓸',
    'fraktur-normal': '𝔬',
    'fraktur-bold': '𝖔',
    'monospace-normal': '𝚘',
    'doublestruck-normal': '𝕠',
  },
  p: {
    'serif-bold': '𝐩',
    'serif-italic': '𝑝',
    'serif-bolditalic': '𝒑',
    'sans-normal': '𝗉',
    'sans-bold': '𝗽',
    'sans-italic': '𝘱',
    'sans-bolditalic': '𝙥',
    'script-normal': '𝓅',
    'script-bold': '𝓹',
    'fraktur-normal': '𝔭',
    'fraktur-bold': '𝖕',
    'monospace-normal': '𝚙',
    'doublestruck-normal': '𝕡',
  },
  q: {
    'serif-bold': '𝐪',
    'serif-italic': '𝑞',
    'serif-bolditalic': '𝒒',
    'sans-normal': '𝗊',
    'sans-bold': '𝗾',
    'sans-italic': '𝘲',
    'sans-bolditalic': '𝙦',
    'script-normal': '𝓆',
    'script-bold': '𝓺',
    'fraktur-normal': '𝔮',
    'fraktur-bold': '𝖖',
    'monospace-normal': '𝚚',
    'doublestruck-normal': '𝕢',
  },
  r: {
    'serif-bold': '𝐫',
    'serif-italic': '𝑟',
    'serif-bolditalic': '𝒓',
    'sans-normal': '𝗋',
    'sans-bold': '𝗿',
    'sans-italic': '𝘳',
    'sans-bolditalic': '𝙧',
    'script-normal': '𝓇',
    'script-bold': '𝓻',
    'fraktur-normal': '𝔯',
    'fraktur-bold': '𝖗',
    'monospace-normal': '𝚛',
    'doublestruck-normal': '𝕣',
  },
  s: {
    'serif-bold': '𝐬',
    'serif-italic': '𝑠',
    'serif-bolditalic': '𝒔',
    'sans-normal': '𝗌',
    'sans-bold': '𝘀',
    'sans-italic': '𝘴',
    'sans-bolditalic': '𝙨',
    'script-normal': '𝓈',
    'script-bold': '𝓼',
    'fraktur-normal': '𝔰',
    'fraktur-bold': '𝖘',
    'monospace-normal': '𝚜',
    'doublestruck-normal': '𝕤',
  },
  t: {
    'serif-bold': '𝐭',
    'serif-italic': '𝑡',
    'serif-bolditalic': '𝒕',
    'sans-normal': '𝗍',
    'sans-bold': '𝘁',
    'sans-italic': '𝘵',
    'sans-bolditalic': '𝙩',
    'script-normal': '𝓉',
    'script-bold': '𝓽',
    'fraktur-normal': '𝔱',
    'fraktur-bold': '𝖙',
    'monospace-normal': '𝚝',
    'doublestruck-normal': '𝕥',
  },
  u: {
    'serif-bold': '𝐮',
    'serif-italic': '𝑢',
    'serif-bolditalic': '𝒖',
    'sans-normal': '𝗎',
    'sans-bold': '𝘂',
    'sans-italic': '𝘶',
    'sans-bolditalic': '𝙪',
    'script-normal': '𝓊',
    'script-bold': '𝓾',
    'fraktur-normal': '𝔲',
    'fraktur-bold': '𝖚',
    'monospace-normal': '𝚞',
    'doublestruck-normal': '𝕦',
  },
  v: {
    'serif-bold': '𝐯',
    'serif-italic': '𝑣',
    'serif-bolditalic': '𝒗',
    'sans-normal': '𝗏',
    'sans-bold': '𝘃',
    'sans-italic': '𝘷',
    'sans-bolditalic': '𝙫',
    'script-normal': '𝓋',
    'script-bold': '𝓿',
    'fraktur-normal': '𝔳',
    'fraktur-bold': '𝖛',
    'monospace-normal': '𝚟',
    'doublestruck-normal': '𝕧',
  },
  w: {
    'serif-bold': '𝐰',
    'serif-italic': '𝑤',
    'serif-bolditalic': '𝒘',
    'sans-normal': '𝗐',
    'sans-bold': '𝘄',
    'sans-italic': '𝘸',
    'sans-bolditalic': '𝙬',
    'script-normal': '𝓌',
    'script-bold': '𝔀',
    'fraktur-normal': '𝔴',
    'fraktur-bold': '𝖜',
    'monospace-normal': '𝚠',
    'doublestruck-normal': '𝕨',
  },
  x: {
    'serif-bold': '𝐱',
    'serif-italic': '𝑥',
    'serif-bolditalic': '𝒙',
    'sans-normal': '𝗑',
    'sans-bold': '𝘅',
    'sans-italic': '𝘹',
    'sans-bolditalic': '𝙭',
    'script-normal': '𝓍',
    'script-bold': '𝔁',
    'fraktur-normal': '𝔵',
    'fraktur-bold': '𝖝',
    'monospace-normal': '𝚡',
    'doublestruck-normal': '𝕩',
  },
  y: {
    'serif-bold': '𝐲',
    'serif-italic': '𝑦',
    'serif-bolditalic': '𝒚',
    'sans-normal': '𝗒',
    'sans-bold': '𝘆',
    'sans-italic': '𝘺',
    'sans-bolditalic': '𝙮',
    'script-normal': '𝓎',
    'script-bold': '𝔂',
    'fraktur-normal': '𝔶',
    'fraktur-bold': '𝖞',
    'monospace-normal': '𝚢',
    'doublestruck-normal': '𝕪',
  },
  z: {
    'serif-bold': '𝐳',
    'serif-italic': '𝑧',
    'serif-bolditalic': '𝒛',
    'sans-normal': '𝗓',
    'sans-bold': '𝘇',
    'sans-italic': '𝘻',
    'sans-bolditalic': '𝙯',
    'script-normal': '𝓏',
    'script-bold': '𝔃',
    'fraktur-normal': '𝔷',
    'fraktur-bold': '𝖟',
    'monospace-normal': '𝚣',
    'doublestruck-normal': '𝕫',
  },
  ı: { 'serif-italic': '𝚤' },
  ȷ: { 'serif-italic': '𝚥' },
  Α: { 'serif-bold': '𝚨', 'serif-italic': '𝛢', 'serif-bolditalic': '𝜜', 'sans-bold': '𝝖', 'sans-bolditalic': '𝞐' },
  Β: { 'serif-bold': '𝚩', 'serif-italic': '𝛣', 'serif-bolditalic': '𝜝', 'sans-bold': '𝝗', 'sans-bolditalic': '𝞑' },
  Γ: { 'serif-bold': '𝚪', 'serif-italic': '𝛤', 'serif-bolditalic': '𝜞', 'sans-bold': '𝝘', 'sans-bolditalic': '𝞒' },
  Δ: { 'serif-bold': '𝚫', 'serif-italic': '𝛥', 'serif-bolditalic': '𝜟', 'sans-bold': '𝝙', 'sans-bolditalic': '𝞓' },
  Ε: { 'serif-bold': '𝚬', 'serif-italic': '𝛦', 'serif-bolditalic': '𝜠', 'sans-bold': '𝝚', 'sans-bolditalic': '𝞔' },
  Ζ: { 'serif-bold': '𝚭', 'serif-italic': '𝛧', 'serif-bolditalic': '𝜡', 'sans-bold': '𝝛', 'sans-bolditalic': '𝞕' },
  Η: { 'serif-bold': '𝚮', 'serif-italic': '𝛨', 'serif-bolditalic': '𝜢', 'sans-bold': '𝝜', 'sans-bolditalic': '𝞖' },
  Θ: { 'serif-bold': '𝚯', 'serif-italic': '𝛩', 'serif-bolditalic': '𝜣', 'sans-bold': '𝝝', 'sans-bolditalic': '𝞗' },
  Ι: { 'serif-bold': '𝚰', 'serif-italic': '𝛪', 'serif-bolditalic': '𝜤', 'sans-bold': '𝝞', 'sans-bolditalic': '𝞘' },
  Κ: { 'serif-bold': '𝚱', 'serif-italic': '𝛫', 'serif-bolditalic': '𝜥', 'sans-bold': '𝝟', 'sans-bolditalic': '𝞙' },
  Λ: { 'serif-bold': '𝚲', 'serif-italic': '𝛬', 'serif-bolditalic': '𝜦', 'sans-bold': '𝝠', 'sans-bolditalic': '𝞚' },
  Μ: { 'serif-bold': '𝚳', 'serif-italic': '𝛭', 'serif-bolditalic': '𝜧', 'sans-bold': '𝝡', 'sans-bolditalic': '𝞛' },
  Ν: { 'serif-bold': '𝚴', 'serif-italic': '𝛮', 'serif-bolditalic': '𝜨', 'sans-bold': '𝝢', 'sans-bolditalic': '𝞜' },
  Ξ: { 'serif-bold': '𝚵', 'serif-italic': '𝛯', 'serif-bolditalic': '𝜩', 'sans-bold': '𝝣', 'sans-bolditalic': '𝞝' },
  Ο: { 'serif-bold': '𝚶', 'serif-italic': '𝛰', 'serif-bolditalic': '𝜪', 'sans-bold': '𝝤', 'sans-bolditalic': '𝞞' },
  Π: { 'serif-bold': '𝚷', 'serif-italic': '𝛱', 'serif-bolditalic': '𝜫', 'sans-bold': '𝝥', 'sans-bolditalic': '𝞟' },
  Ρ: { 'serif-bold': '𝚸', 'serif-italic': '𝛲', 'serif-bolditalic': '𝜬', 'sans-bold': '𝝦', 'sans-bolditalic': '𝞠' },
  ϴ: { 'serif-bold': '𝚹', 'serif-italic': '𝛳', 'serif-bolditalic': '𝜭', 'sans-bold': '𝝧', 'sans-bolditalic': '𝞡' },
  Σ: { 'serif-bold': '𝚺', 'serif-italic': '𝛴', 'serif-bolditalic': '𝜮', 'sans-bold': '𝝨', 'sans-bolditalic': '𝞢' },
  Τ: { 'serif-bold': '𝚻', 'serif-italic': '𝛵', 'serif-bolditalic': '𝜯', 'sans-bold': '𝝩', 'sans-bolditalic': '𝞣' },
  Υ: { 'serif-bold': '𝚼', 'serif-italic': '𝛶', 'serif-bolditalic': '𝜰', 'sans-bold': '𝝪', 'sans-bolditalic': '𝞤' },
  Φ: { 'serif-bold': '𝚽', 'serif-italic': '𝛷', 'serif-bolditalic': '𝜱', 'sans-bold': '𝝫', 'sans-bolditalic': '𝞥' },
  Χ: { 'serif-bold': '𝚾', 'serif-italic': '𝛸', 'serif-bolditalic': '𝜲', 'sans-bold': '𝝬', 'sans-bolditalic': '𝞦' },
  Ψ: { 'serif-bold': '𝚿', 'serif-italic': '𝛹', 'serif-bolditalic': '𝜳', 'sans-bold': '𝝭', 'sans-bolditalic': '𝞧' },
  Ω: { 'serif-bold': '𝛀', 'serif-italic': '𝛺', 'serif-bolditalic': '𝜴', 'sans-bold': '𝝮', 'sans-bolditalic': '𝞨' },
  '∇': { 'serif-bold': '𝛁', 'serif-italic': '𝛻', 'serif-bolditalic': '𝜵', 'sans-bold': '𝝯', 'sans-bolditalic': '𝞩' },
  α: { 'serif-bold': '𝛂', 'serif-italic': '𝛼', 'serif-bolditalic': '𝜶', 'sans-bold': '𝝰', 'sans-bolditalic': '𝞪' },
  β: { 'serif-bold': '𝛃', 'serif-italic': '𝛽', 'serif-bolditalic': '𝜷', 'sans-bold': '𝝱', 'sans-bolditalic': '𝞫' },
  γ: { 'serif-bold': '𝛄', 'serif-italic': '𝛾', 'serif-bolditalic': '𝜸', 'sans-bold': '𝝲', 'sans-bolditalic': '𝞬' },
  δ: { 'serif-bold': '𝛅', 'serif-italic': '𝛿', 'serif-bolditalic': '𝜹', 'sans-bold': '𝝳', 'sans-bolditalic': '𝞭' },
  ε: { 'serif-bold': '𝛆', 'serif-italic': '𝜀', 'serif-bolditalic': '𝜺', 'sans-bold': '𝝴', 'sans-bolditalic': '𝞮' },
  ζ: { 'serif-bold': '𝛇', 'serif-italic': '𝜁', 'serif-bolditalic': '𝜻', 'sans-bold': '𝝵', 'sans-bolditalic': '𝞯' },
  η: { 'serif-bold': '𝛈', 'serif-italic': '𝜂', 'serif-bolditalic': '𝜼', 'sans-bold': '𝝶', 'sans-bolditalic': '𝞰' },
  θ: { 'serif-bold': '𝛉', 'serif-italic': '𝜃', 'serif-bolditalic': '𝜽', 'sans-bold': '𝝷', 'sans-bolditalic': '𝞱' },
  ι: { 'serif-bold': '𝛊', 'serif-italic': '𝜄', 'serif-bolditalic': '𝜾', 'sans-bold': '𝝸', 'sans-bolditalic': '𝞲' },
  κ: { 'serif-bold': '𝛋', 'serif-italic': '𝜅', 'serif-bolditalic': '𝜿', 'sans-bold': '𝝹', 'sans-bolditalic': '𝞳' },
  λ: { 'serif-bold': '𝛌', 'serif-italic': '𝜆', 'serif-bolditalic': '𝝀', 'sans-bold': '𝝺', 'sans-bolditalic': '𝞴' },
  μ: { 'serif-bold': '𝛍', 'serif-italic': '𝜇', 'serif-bolditalic': '𝝁', 'sans-bold': '𝝻', 'sans-bolditalic': '𝞵' },
  ν: { 'serif-bold': '𝛎', 'serif-italic': '𝜈', 'serif-bolditalic': '𝝂', 'sans-bold': '𝝼', 'sans-bolditalic': '𝞶' },
  ξ: { 'serif-bold': '𝛏', 'serif-italic': '𝜉', 'serif-bolditalic': '𝝃', 'sans-bold': '𝝽', 'sans-bolditalic': '𝞷' },
  ο: { 'serif-bold': '𝛐', 'serif-italic': '𝜊', 'serif-bolditalic': '𝝄', 'sans-bold': '𝝾', 'sans-bolditalic': '𝞸' },
  π: { 'serif-bold': '𝛑', 'serif-italic': '𝜋', 'serif-bolditalic': '𝝅', 'sans-bold': '𝝿', 'sans-bolditalic': '𝞹' },
  ρ: { 'serif-bold': '𝛒', 'serif-italic': '𝜌', 'serif-bolditalic': '𝝆', 'sans-bold': '𝞀', 'sans-bolditalic': '𝞺' },
  ς: { 'serif-bold': '𝛓', 'serif-italic': '𝜍', 'serif-bolditalic': '𝝇', 'sans-bold': '𝞁', 'sans-bolditalic': '𝞻' },
  σ: { 'serif-bold': '𝛔', 'serif-italic': '𝜎', 'serif-bolditalic': '𝝈', 'sans-bold': '𝞂', 'sans-bolditalic': '𝞼' },
  τ: { 'serif-bold': '𝛕', 'serif-italic': '𝜏', 'serif-bolditalic': '𝝉', 'sans-bold': '𝞃', 'sans-bolditalic': '𝞽' },
  υ: { 'serif-bold': '𝛖', 'serif-italic': '𝜐', 'serif-bolditalic': '𝝊', 'sans-bold': '𝞄', 'sans-bolditalic': '𝞾' },
  φ: { 'serif-bold': '𝛗', 'serif-italic': '𝜑', 'serif-bolditalic': '𝝋', 'sans-bold': '𝞅', 'sans-bolditalic': '𝞿' },
  χ: { 'serif-bold': '𝛘', 'serif-italic': '𝜒', 'serif-bolditalic': '𝝌', 'sans-bold': '𝞆', 'sans-bolditalic': '𝟀' },
  ψ: { 'serif-bold': '𝛙', 'serif-italic': '𝜓', 'serif-bolditalic': '𝝍', 'sans-bold': '𝞇', 'sans-bolditalic': '𝟁' },
  ω: { 'serif-bold': '𝛚', 'serif-italic': '𝜔', 'serif-bolditalic': '𝝎', 'sans-bold': '𝞈', 'sans-bolditalic': '𝟂' },
  '∂': { 'serif-bold': '𝛛', 'serif-italic': '𝜕', 'serif-bolditalic': '𝝏', 'sans-bold': '𝞉', 'sans-bolditalic': '𝟃' },
  ϵ: { 'serif-bold': '𝛜', 'serif-italic': '𝜖', 'serif-bolditalic': '𝝐', 'sans-bold': '𝞊', 'sans-bolditalic': '𝟄' },
  ϑ: { 'serif-bold': '𝛝', 'serif-italic': '𝜗', 'serif-bolditalic': '𝝑', 'sans-bold': '𝞋', 'sans-bolditalic': '𝟅' },
  ϰ: { 'serif-bold': '𝛞', 'serif-italic': '𝜘', 'serif-bolditalic': '𝝒', 'sans-bold': '𝞌', 'sans-bolditalic': '𝟆' },
  ϕ: { 'serif-bold': '𝛟', 'serif-italic': '𝜙', 'serif-bolditalic': '𝝓', 'sans-bold': '𝞍', 'sans-bolditalic': '𝟇' },
  ϱ: { 'serif-bold': '𝛠', 'serif-italic': '𝜚', 'serif-bolditalic': '𝝔', 'sans-bold': '𝞎', 'sans-bolditalic': '𝟈' },
  ϖ: { 'serif-bold': '𝛡', 'serif-italic': '𝜛', 'serif-bolditalic': '𝝕', 'sans-bold': '𝞏', 'sans-bolditalic': '𝟉' },
  Ϝ: { 'serif-bold': '𝟊' },
  ϝ: { 'serif-bold': '𝟋' },
  '0': { 'serif-bold': '𝟎', 'doublestruck-normal': '𝟘', 'sans-normal': '𝟢', 'sans-bold': '𝟬', 'monospace-normal': '𝟶' },
  '1': { 'serif-bold': '𝟏', 'doublestruck-normal': '𝟙', 'sans-normal': '𝟣', 'sans-bold': '𝟭', 'monospace-normal': '𝟷' },
  '2': { 'serif-bold': '𝟐', 'doublestruck-normal': '𝟚', 'sans-normal': '𝟤', 'sans-bold': '𝟮', 'monospace-normal': '𝟸' },
  '3': { 'serif-bold': '𝟑', 'doublestruck-normal': '𝟛', 'sans-normal': '𝟥', 'sans-bold': '𝟯', 'monospace-normal': '𝟹' },
  '4': { 'serif-bold': '𝟒', 'doublestruck-normal': '𝟜', 'sans-normal': '𝟦', 'sans-bold': '𝟰', 'monospace-normal': '𝟺' },
  '5': { 'serif-bold': '𝟓', 'doublestruck-normal': '𝟝', 'sans-normal': '𝟧', 'sans-bold': '𝟱', 'monospace-normal': '𝟻' },
  '6': { 'serif-bold': '𝟔', 'doublestruck-normal': '𝟞', 'sans-normal': '𝟨', 'sans-bold': '𝟲', 'monospace-normal': '𝟼' },
  '7': { 'serif-bold': '𝟕', 'doublestruck-normal': '𝟟', 'sans-normal': '𝟩', 'sans-bold': '𝟳', 'monospace-normal': '𝟽' },
  '8': { 'serif-bold': '𝟖', 'doublestruck-normal': '𝟠', 'sans-normal': '𝟪', 'sans-bold': '𝟴', 'monospace-normal': '𝟾' },
  '9': { 'serif-bold': '𝟗', 'doublestruck-normal': '𝟡', 'sans-normal': '𝟫', 'sans-bold': '𝟵', 'monospace-normal': '𝟿' },
};

export const fontPrefixMap: { [prefix: string]: mathFontface } = {
  double: 'doublestruck-normal',
  mathbb: 'doublestruck-normal',
  fraktur: 'fraktur-normal',
  frak: 'fraktur-normal',
  mathfrak: 'fraktur-normal',
  Fraktur: 'fraktur-bold',
  Frak: 'fraktur-bold',
  script: 'script-normal',
  Script: 'script-bold',
  mono: 'monospace-normal',
  it: 'serif-italic',
  mathit: 'serif-italic',
  bf: 'serif-bold',
  mathbf: 'serif-bold',
  bfit: 'serif-bolditalic',
  sf: 'sans-normal',
  mathsf: 'sans-normal',
  Sf: 'sans-bold',
  si: 'sans-italic',
  sbi: 'sans-bolditalic',
};

export function translateFont(c: string, fontface: mathFontface): string {
  if (!mathFonts.hasOwnProperty(c)) {
    return c;
  }
  const font = mathFonts[c];
  if (!font.hasOwnProperty(fontface)) {
    return c;
  }
  const res = font[fontface];
  if (res === undefined) {
    return c;
  }
  return res;
}
